In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
car = pd.read_csv("E:\VAIBHAV\Machine Learning Project data\Car prediction\k.csv")
car.head()

,name,company,year,price,kms_covered,fuel_type
0,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
1,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2015,Ask For Price,"59,000 kms",Diesel

In [3]:
car.shape

(891, 6)

In [4]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         891 non-null    object
 1   company      891 non-null    object
 2   year         891 non-null    object
 3   price        891 non-null    object
 4   kms_covered  839 non-null    object
 5   fuel_type    836 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [5]:
car.year.unique()

array(['2006', '2018', '2014', '2015', '2012', '2013', '2016', '2010',
       '2007', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

## Quality
- year has many non-year values
- year object to int
- price has Aks for price
- price object to int
- kms_driven has kms with int
- kms_driven object to int
- kms_driven has nan values
- fuel_type has nan values
- keep first 3 words of name

## Cleaning

In [6]:
backup = car.copy()

In [7]:
car['year']

0      2006
1      2018
2      2014
3      2014
4      2015
       ...
886    zest
887    2018
888    2013
889    2014
890    2014
Name: year, Length: 891, dtype: object

In [8]:
car['year'].str.isnumeric().sum()

841

In [9]:
car = car[car['year'].str.isnumeric()]

In [10]:
car.head()

,name,company,year,price,kms_covered,fuel_type
0,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
1,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2015,Ask For Price,"59,000 kms",Diesel

In [11]:
car.year=car['year'].astype(int)

In [12]:
car = car[car['price']!= "Ask For Price"]

In [13]:
car.head()

,name,company,year,price,kms_covered,fuel_type
0,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
5,Ford Figo,Ford,2012,"1,75,000","41,000 kms",Diesel
6,Hyundai Eon,Hyundai,2013,"1,90,000","25,000 kms",Petrol

In [14]:
car.price= car['price'].str.replace(',','').astype(int)

In [15]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 818 entries, 0 to 890
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         818 non-null    object
 1   company      818 non-null    object
 2   year         818 non-null    int32
 3   price        818 non-null    int32
 4   kms_covered  818 non-null    object
 5   fuel_type    815 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.3+ KB

In [16]:
 car.kms_covered= car['kms_covered'].str.split(' ').str.get(0).str.replace(',','')

In [17]:
car= car[car['kms_covered'].str.isnumeric()]
car

,name,company,year,price,kms_covered,fuel_type
0,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
5,Ford Figo,Ford,2012,175000,41000,Diesel
6,Hyundai Eon,Hyundai,2013,190000,25000,Petrol
...,...,...,...,...,...,...
882,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
884,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
885,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
887,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
888,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [18]:
car.kms_covered = car['kms_covered'].astype(int)

In [19]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 816 entries, 0 to 888
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         816 non-null    object
 1   company      816 non-null    object
 2   year         816 non-null    int32
 3   price        816 non-null    int32
 4   kms_covered  816 non-null    int32
 5   fuel_type    815 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB

In [20]:
car= car[~car['fuel_type'].isna()]

In [21]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 815 entries, 0 to 888
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         815 non-null    object
 1   company      815 non-null    object
 2   year         815 non-null    int32
 3   price        815 non-null    int32
 4   kms_covered  815 non-null    int32
 5   fuel_type    815 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.0+ KB

In [22]:
car['name'] = car['name'].str.split(' ').str.slice(0,3).str.join(' ')

C:\Users\akash\AppData\Local\Temp\ipykernel_18888\96074993.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['name'] = car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [23]:
car = car.reset_index(drop=True)

In [24]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815 entries, 0 to 814
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         815 non-null    object
 1   company      815 non-null    object
 2   year         815 non-null    int32
 3   price        815 non-null    int32
 4   kms_covered  815 non-null    int32
 5   fuel_type    815 non-null    object
dtypes: int32(3), object(3)
memory usage: 28.8+ KB

In [25]:
car.describe()

              year         price    kms_covered
count   815.000000  8.150000e+02     815.000000
mean   2012.451534  4.121246e+05   46277.096933
std       4.000896  4.753339e+05   34318.459638
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.925000e+05   56879.000000
max    2019.000000  8.500003e+06  400000.000000

In [26]:
car= car[car['price']<6e6].reset_index(drop=True)

In [27]:
car

                       name   company  year   price  kms_covered fuel_type
0       Mahindra Jeep CL550  Mahindra  2006  425000           40    Diesel
1         Hyundai Grand i10   Hyundai  2014  325000        28000    Petrol
2    Ford EcoSport Titanium      Ford  2014  575000        36000    Diesel
3                 Ford Figo      Ford  2012  175000        41000    Diesel
4               Hyundai Eon   Hyundai  2013  190000        25000    Petrol
..                      ...       ...   ...     ...          ...       ...
809      Maruti Suzuki Ritz    Maruti  2011  270000        50000    Petrol
810          Tata Indica V2      Tata  2009  110000        30000    Diesel
811    Toyota Corolla Altis    Toyota  2009  300000       132000    Petrol
812            Tata Zest XM      Tata  2018  260000        27000    Diesel
813      Mahindra Quanto C8  Mahindra  2013  390000        40000    Diesel

[814 rows x 6 columns]

In [28]:
car.to_csv('clean_car1.csv')

## Model

In [29]:
x = car.drop(columns='price')
y = car['price']

In [30]:
x

                       name   company  year  kms_covered fuel_type
0       Mahindra Jeep CL550  Mahindra  2006           40    Diesel
1         Hyundai Grand i10   Hyundai  2014        28000    Petrol
2    Ford EcoSport Titanium      Ford  2014        36000    Diesel
3                 Ford Figo      Ford  2012        41000    Diesel
4               Hyundai Eon   Hyundai  2013        25000    Petrol
..                      ...       ...   ...          ...       ...
809      Maruti Suzuki Ritz    Maruti  2011        50000    Petrol
810          Tata Indica V2      Tata  2009        30000    Diesel
811    Toyota Corolla Altis    Toyota  2009       132000    Petrol
812            Tata Zest XM      Tata  2018        27000    Diesel
813      Mahindra Quanto C8  Mahindra  2013        40000    Diesel

[814 rows x 5 columns]

In [31]:
y

0      425000
1      325000
2      575000
3      175000
4      190000
        ...
809    270000
810    110000
811    300000
812    260000
813    390000
Name: price, Length: 814, dtype: int32

In [32]:
from sklearn.model_selection import train_test_split
x_train , x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,)

In [33]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [34]:
ohe = OneHotEncoder()
ohe.fit(x[['name','company','fuel_type']])

OneHotEncoder()

In [35]:
ohe.categories_

[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
        'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
        'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
        'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
        'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
        'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
        'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
        'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
        'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
        'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend',
        'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
        'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
        'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
        'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
        'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
        'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
        'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
        'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
        'Land Rover Freelander', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
        'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
        'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
        'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
        'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
        'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
        'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
        'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
        'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
        'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
        'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
        'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [36]:
column_trains = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                       remainder='passthrough')

In [37]:
model = LinearRegression()

In [38]:
pipe = make_pipeline(column_trains,model)
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [39]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [40]:
y_pred = pipe.predict(x_test)

In [41]:
y_pred

array([ 400838.95571943, 1051299.33760204,  304093.52312905,
        598486.16517533,  269871.63443882,  361202.62843997,
        153200.43294539,  580173.76553309,  256329.50311306,
        562331.16407475,  408683.26038999,  328704.54728282,
        176313.18804346,  532381.03698974,  525802.69901516,
        -32834.05595691,  465759.42969067,  248391.21176156,
        161183.92526133,  384565.08936651,  169416.09522638,
        421191.82215343,  366319.01675103,  180920.54490039,
         57829.93610376,  155105.23463533,  713079.11984795,
        450299.10408551,  360729.8486542 ,  532381.03698974,
        280879.05371001,  204018.29249579,  619524.95189986,
        137846.62353306,  383335.66302142,  392862.55616327,
        411091.06116832,  726293.09867323,  333670.07825634,
        361072.21016139,  194926.11741087,   72133.15510061,
        498430.97668211,  114631.03528029,  257035.26756097,
        596555.54295018,  285672.33008364, -202678.63482072,
        619524.95189986,  273104.29353401,  246035.61242519,
        280904.44382307,   47210.55394784,  240679.18860186,
        368016.74877229,  363733.71009249,  586594.54071683,
        139308.0800206 ,  172186.24568424,  428929.77298152,
         57293.44122361,  222529.40423894,  251400.56122677,
       -177091.27201126,  336495.91338546,  141284.54187142,
        443002.41034544,  256824.06971209,  341038.52677898,
        562331.16407475,  291631.93210772,  830025.83237165,
        358624.93027744, 1498488.90119823,  391488.02689227,
        366889.46295898,  437474.3754705 ,  470534.13450308,
        678841.26218143,  285316.20232351,   14873.77105319,
        453017.04667114,  205012.11399617,  581825.22901573,
        713079.11984795,  501264.33394057,  243674.55050272,
        282629.64525616,  214676.05383691,  434877.20301531,
        676878.48894097,  509158.42252139,  492145.48526604,
        373072.3531286 ,  379885.17759027, -164442.61667125,
        228314.30536722,  269871.63443882,  297140.32175836,
        589963.78967251,  610304.17144575,  142529.30554339,
         34724.87103394,  403079.35160422,  627507.85456122,
        353920.26464473,  -16449.854585  ,  262861.63472866,
        411550.61398097,  153200.43294539,  179256.38563263,
       2205008.54215048,   53577.5566035 ,  370722.54408615,
        598129.37186845,  160410.17673323,  407020.0266405 ,
        363801.55903229,  594508.59414035,  558218.22359796,
        654538.92825598,  645709.28340045,  558234.78670284,
        240364.41603012,  709912.95364614,  389857.56778212,
        981633.19996331,  534030.04871406,  491640.15953822,
         22253.01872332,  372924.77104875,  418009.43434309,
        210317.54629402,  558822.80699775,  593280.81032849,
        436895.16448586,  517581.29251888, -116734.9692655 ,
        627878.57568619,  534246.92957908,  240364.41603012,
         49495.04697312,  339035.1342196 ,  196682.49741993,
         83226.63116756,  278281.21378207,  199919.58801434,
        301861.36954208,  339378.6138538 , 1011569.29472215,
        477079.47920269,  280369.33040565,  376265.19699581,
        397065.2522167 , 1583520.61004974,  843464.70828999,
        619135.2329708 ,  462945.4014434 ,  -84113.59778946,
        425756.79005262,  318670.13325045,  343261.432963  ,
        240679.18860186])

In [42]:
r2_score(y_test,y_pred)

0.6835501331471412

In [43]:
scores = []
for i in range (1000):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
    model = LinearRegression()
    pipe = make_pipeline(column_trains,model)
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    print(r2_score(y_test,y_pred),i)
    scores.append(r2_score(y_test,y_pred))

0.6789845996376324 0
0.6188878488384618 1
0.6602264866658625 2
0.6952893142875227 3
0.5563165458097534 4
0.5829930628157236 5
0.6035377256957926 6
0.6419404617756199 7
0.5504507474513975 8
0.47200655779175427 9
0.481993354992441 10
0.6558535927377289 11
0.7379177579971513 12
0.6706955141441364 13
0.7630012792615056 14
0.5837335616736208 15
0.6677729303509794 16
0.7519333397801256 17
0.6574674042257849 18
0.6187387383417469 19
0.6339349274589059 20
0.624333461328426 21
0.6901243740161822 22
0.5511881480972597 23
0.6028261122028894 24
0.4594849263394183 25
0.6839314697424315 26
0.6824603253371626 27
0.628231127362509 28
0.4345509681675126 29
0.7253569163499507 30
0.7354190508275958 31
0.5711830858765001 32
0.5998360010473285 33
0.6804927859827679 34
0.6408129802850586 35
0.5617620477009626 36
0.648200827130951 37
0.48630699175260883 38
0.6835902925375279 39
0.613907531912637 40
0.5827112577178177 41
0.5750728276346027 42
0.5142351942186212 43
0.6639607025265413 44
0.6994265491615946 45
0.6304611469742527 46
0.5226433792392169 47
0.7603227770027137 48
0.5365099990528914 49
0.6654789538107807 50
0.7729505293202108 51
0.6882159901017703 52
0.6578248530745978 53
0.6618964571387764 54
0.5684681015278774 55
0.6245107486174285 56
0.5909223526041278 57
0.7270651872207103 58
0.5815666956701928 59
0.6068906767429652 60
0.7134925382381418 61
0.6721097577910102 62
0.5436570752377123 63
0.6551570469091662 64
0.5715958616226324 65
0.6145023576582291 66
0.5336007438340131 67
0.6246673775700475 68
0.653293501379572 69
0.5481781147006675 70
0.6989156979458921 71
0.646536586579183 72
0.5873867842894498 73
0.6403436429967635 74
0.7477017956723169 75
0.5687172956521038 76
0.6770404818173954 77
0.6919189356804947 78
0.6645203267141642 79
0.6999907276172682 80
0.6696015595734619 81
0.5447997289429065 82
0.5738561501616553 83
0.665360899313985 84
0.6385750656748543 85
0.6072429092748732 86
0.5921854071622956 87
0.738103966375227 88
0.6105294041230818 89
0.7046446631659667 90
0.40169450892905756 91
0.6415101354741144 92
0.6479444916690189 93
0.6892706783651807 94
0.6620908939920542 95
0.6265796092566918 96
0.5900637454371503 97
0.6846013707640546 98
0.6886123117089262 99
0.6953741939801517 100
0.7119100877391651 101
0.6911867384320238 102
0.7107834532928905 103
0.4983960020003112 104
0.5471456247360629 105
0.6828184114322164 106
0.6387362372157648 107
0.7117613897337853 108
0.5747476366185192 109
0.6682593481526709 110
0.6347818907925135 111
0.6165844898724722 112
0.5089939628252904 113
0.7292110079545222 114
0.7617241094399635 115
0.5392937993268786 116
0.5214603470846066 117
0.6010425719883428 118
0.6809826968607109 119
0.7391829864151054 120
0.6312544413856653 121
0.7181621263188656 122
0.7617069306620068 123
0.4842805552172559 124
0.755715500244086 125
0.6479847514020367 126
0.5534314904580079 127
0.6617022513673194 128
0.7322185644901805 129
0.7843992476398107 130
0.6956046612862036 131
0.6525195345743755 132
0.7269814517400444 133
0.7048109633213171 134
0.6071870380072582 135
0.6314603780048341 136
0.6312181299132609 137
0.6255751926175159 138
0.6826663883383575 139
0.5835431378403149 140
0.6575208311718761 141
0.6200443630065756 142
0.741739846730319 143
0.5278660924233848 144
0.6599676938593242 145
0.6499273178282586 146
0.6357003964030987 147
0.7353185436156211 148
0.5362104873844056 149
0.6486171546641415 150
0.6225039579135185 151
0.6733554588352958 152
0.5458331119977397 153
0.5334464325571033 154
0.7279927306861975 155
0.658615175124784 156
0.6298470096063787 157
0.6994620702737586 158
0.6449480501578964 159
0.6330140882425741 160
0.5304847175670759 161
0.6199647807263039 162
0.690154692931037 163
0.6663971631956809 164
0.6730231405518403 165
0.6706109871976441 166
0.5567882671681927 167
0.7059803773946067 168
0.47966434062635765 169
0.657669428330317 170
0.5598055131179358 171
0.4744487645977158 172
0.6646029730878696 173
0.49847049259856235 174
0.7778136655957908 175
0.7655456853495968 176
0.7258848900018964 177
0.6768272915897195 178
0.7994521256958689 179
0.5991054056376799 180
0.671941005984132 181
0.5963402519720156 182
0.6069400221521007 183
0.7345348318198677 184
0.6277052771298168 185
0.6788010882576587 186
0.7301440949109432 187
0.6041534128827565 188
0.7043773101511547 189
0.7307186465114066 190
0.6299282928125917 191
0.690114955303821 192
0.7096656491936628 193
0.6345567435565487 194
0.611615113971069 195
0.6158110425993106 196
0.7091766931199105 197
0.4075175566700129 198
0.761038718395327 199
0.6342368142813869 200
0.6648312955612279 201
0.6071000046204358 202
0.6497601196285188 203
0.7788589054438306 204
0.667913785338482 205
0.5966890501647082 206
0.4353412395051346 207
0.6091436953384315 208
0.6646402226093799 209
0.6673648599766879 210
0.7039981590217829 211
0.6503556850013557 212
0.5844842651158624 213
0.62298145168506 214
0.6997861389610807 215
0.6063913626302103 216
0.6726365776352614 217
0.6575876259495631 218
0.5382349030244913 219
0.49708163101597025 220
0.7084895637052244 221
0.6677570551266501 222
0.6915372268684216 223
0.6179115415488764 224
0.7279251329217258 225
0.3297841953129851 226
0.5691823954428398 227
0.6044055031819476 228
0.43931099354371017 229
0.6562135008643548 230
0.742268675656679 231
0.6105290473392413 232
0.7053858248133491 233
0.5173047029289963 234
0.4916928535497501 235
0.586016349088655 236
0.5699009443344716 237
0.573179813496405 238
0.5892057297469838 239
0.5750955766490627 240
0.6017664476374602 241
0.588881403898815 242
0.5973253883028908 243
0.6612926936722743 244
0.7394601526572337 245
0.5320483894496817 246
0.5867251833248404 247
0.7146112282383839 248
0.6737439300818202 249
0.6389306724141637 250
0.6426905157391853 251
0.7085073400832165 252
0.7129318095586887 253
0.8197591490786995 254
0.7424781742937038 255
0.7271146781765441 256
0.7177627767270419 257
0.5608900481208754 258
0.5509991376551757 259
0.5408909737388317 260
0.7051601287175708 261
0.6342582265288959 262
0.554346817699545 263
0.6355100691173368 264
0.7444692903303538 265
0.48744109662960144 266
0.5601382049202426 267
0.6542041341932492 268
0.6595544899240937 269
0.706827317581773 270
0.6762535907566259 271
0.5372754340785408 272
0.5983658360451989 273
0.5359228418439259 274
0.7210805322303853 275
0.6525290156995879 276
0.5704531071113148 277
0.5979088477793072 278
0.7134184033853885 279
0.6159083238432081 280
0.5851487690859287 281
0.6781901920632136 282
0.6700442607865165 283
0.7287188653841643 284
0.6738868770990034 285
0.7056013227436155 286
0.5163566852542951 287
0.5717194029363423 288
0.6689225061505266 289
0.5320274071265185 290
0.6646609928746159 291
0.6758253419639622 292
0.5673227347405283 293
0.5998201962791243 294
0.6931240449545395 295
0.7642300607850502 296
0.5846386867515536 297
0.6934720906497116 298
0.648487659239134 299
0.5372953443831197 300
0.6179598359001088 301
0.7322569823253269 302
0.6589138864004707 303
0.7288631524922065 304
0.7241334499466829 305
0.7129553963799355 306
0.6819222838132553 307
0.6352085661783994 308
0.6923031035479482 309
0.49852126653269946 310
0.7218244853039149 311
0.5501411560591839 312
0.5972431618121528 313
0.7033822910747127 314
0.6099791336258085 315
0.7804732334080624 316
0.5863401997522342 317
0.6504626562429578 318
0.7794664933682884 319
0.7634763587560973 320
0.6024314975728476 321
0.6701952750350915 322
0.6341851140128905 323
0.6249750420716147 324
0.6867392692072335 325
0.6531390357361992 326
0.7143371562252108 327
0.6485683233334542 328
0.6635530566338097 329
0.6483995453957965 330
0.6345588692255297 331
0.6997746952891759 332
0.6929336497017431 333
0.7067414059823262 334
0.5136611493020612 335
0.5850063957068321 336
0.6950660587571675 337
0.7347552289451221 338
0.6459465821951058 339
0.618633899749256 340
0.5985047430661241 341
0.7827109911285454 342
0.627260515097203 343
0.7167010942756665 344
0.5191555184736822 345
0.5457100335256541 346
0.6588415744406098 347
0.5363273491303281 348
0.7306991702321677 349
0.6596829794737487 350
0.571058443291399 351
0.626289845458849 352
0.7520809217476622 353
0.5346733855300418 354
0.6582221300094003 355
0.6660734892390776 356
0.5208449093112069 357
0.5115252606036585 358
0.5739164517189823 359
0.6602333697015552 360
0.6920264223256217 361
0.677566153039161 362
0.594369228820468 363
0.6887940692788461 364
0.691000417139382 365

0.5689247427013362 366
0.6971999013195965 367
0.5271140968801641 368
0.7446917089837868 369
0.6699669769573147 370
0.6396641332473993 371
0.6626481812362093 372
0.6900108144174668 373
0.5761183878958434 374
0.640328020765399 375
0.5738967186624513 376
0.6783579680852714 377
0.6322133999587122 378
0.6569972457762306 379
0.504803511165689 380
0.6867235318456626 381
0.5833830076752409 382
0.6707556261700403 383
0.5958224611805714 384
0.6081451289104842 385
0.6653240828513305 386
0.6698854867219455 387
0.5554557564842886 388
0.5974462701559324 389
0.6870333282982606 390
0.6630417452058641 391
0.5976130587692275 392
0.575952939951182 393
0.7252382858167761 394
0.7558720554503582 395
0.6901225480682268 396
0.5971644144224891 397
0.6345371959863413 398
0.7210501118711314 399
0.6159817790518678 400
0.6181755587774993 401
0.5403061526758841 402
0.5364523915982402 403
0.5265266676414295 404
0.7427201731777937 405
0.5365976371154986 406
0.5481865741264591 407
0.7810137875421017 408
0.7247619862672283 409
0.5417816410243969 410
0.5368679176494446 411
0.7321948404498687 412
0.6879958734064555 413
0.734440678329046 414
0.6753632866207593 415
0.6778903052680536 416
0.690802155416145 417
0.6185271069955689 418
0.6154374326987005 419
0.7099042358963998 420
0.6440077796225028 421
0.6833336989694558 422
0.6898932184099649 423
0.4620398235079185 424
0.6789412501675394 425
0.5662661524906027 426
0.6868378171085283 427
0.5817512471530244 428
0.579770055547048 429
0.5721043631211273 430
0.567048640799066 431
0.7070747944530996 432
0.6778066919676053 433
0.7171059324326265 434
0.5910075231630185 435
0.5976535571805219 436
0.6030326116234631 437
0.5057373197384257 438
0.7720926535752792 439
0.661056025173123 440
0.7265673342841081 441
0.6617738951394535 442
0.5499103038950728 443
0.6615251593918012 444
0.5843836115228466 445
0.538802071376238 446
0.7418510401025984 447
0.7369754069196338 448
0.6626846909047976 449
0.7131510133371279 450
0.6049871749277561 451
0.7061618410135406 452
0.5862760929234183 453
0.6744046718439854 454
0.6086828174207721 455
0.7248455196614992 456
0.5460419856099942 457
0.7847476000462911 458
0.5898571684020133 459
0.6490563133650249 460
0.7062885829496387 461
0.5851576944673927 462
0.7510222575750916 463
0.6305666734633129 464
0.6190298334265902 465
0.5354862831064731 466
0.7660748560756372 467
0.72096175975436 468
0.5388199610561412 469
0.7205328690934012 470
0.6955893112449566 471
0.5407145652806471 472
0.6139177652504394 473
0.7025251340573208 474
0.709071145115269 475
0.5515433312414657 476
0.6725434689315098 477
0.6529022229371211 478
0.5867937224359492 479
0.6039847700755592 480
0.673158363451394 481
0.6751439098919304 482
0.6005627298563168 483
0.5599414306158232 484
0.7044103760935267 485
0.6788817019506403 486
0.7215100815992583 487
0.6039004980025436 488
0.6790941593615638 489
0.4672428220506726 490
0.47351284188599874 491
0.6579257647044112 492
0.6344255759370889 493
0.5704315657462032 494
0.5328406994274224 495
0.6851676632859309 496
0.7100198869768841 497
0.7192376704508143 498
0.4705090696645384 499
0.6649647311208156 500
0.7958202552301649 501
0.5598537855397162 502
0.6221627557453977 503
0.6795065142894214 504
0.7079660575602023 505
0.6349995814842362 506
0.5446760101273111 507
0.7140107543664467 508
0.693170870450948 509
0.6816009020666958 510
0.7352198837009213 511
0.48263741903265056 512
0.5178069088827142 513
0.6911580879769046 514
0.6255493538150856 515
0.6408160061349675 516
0.7592095813118939 517
0.701700492618938 518
0.7203990596814271 519
0.5595977202148024 520
0.5741138180017833 521
0.7595401644810553 522
0.6243426053050873 523
0.7193635847363133 524
0.5161435474904996 525
0.711624052324699 526
0.5497159999836209 527
0.7495136224949688 528
0.44799801385092763 529
0.6708477735727164 530
0.6199780286044598 531
0.5822951053407719 532
0.6479936119721081 533
0.6112326923381199 534
0.7467871058629186 535
0.7121890757619007 536
0.7418730326983346 537
0.7624386650139825 538
0.6744098947322206 539
0.7274447003425808 540
0.6886063544970935 541
0.6782489726561167 542
0.6580678359375501 543
0.5555414404279584 544
0.7120102561520667 545
0.5954564365638115 546
0.7283574724569706 547
0.7343035662329309 548
0.6326888678994678 549
0.7202051265510894 550
0.5546475969232832 551
0.6681560425395716 552
0.6961276541945183 553
0.5641633875518872 554
0.490799676813682 555
0.7354927191110429 556
0.6534993267675302 557
0.6720858361654722 558
0.7130681680206467 559
0.6141765619295216 560
0.7022506512359015 561
0.5765491617540646 562
0.5183552690895395 563
0.7236628415222437 564
0.6448795728262632 565
0.7734655858004124 566
0.6713077367193283 567
0.6133969591961959 568
0.6290625735764559 569
0.6013463492430557 570
0.7741686265944961 571
0.7583462717909322 572
0.5433634682016962 573
0.6697191821555719 574
0.690806666231505 575
0.7359078763785634 576
0.597907144674596 577
0.5943289133021699 578
0.6874591121586802 579
0.5064556035522558 580
0.584128760742003 581
0.638368374986654 582
0.6629973958320248 583
0.6227510068840801 584
0.5425454883531258 585
0.5430396877731147 586
0.6020653513420592 587
0.6602632261377837 588
0.579176647888251 589
0.6969171809682583 590
0.6838378705392953 591
0.5248149483738007 592
0.8141911266828066 593
0.6543405003397275 594
0.6834628567481524 595
0.8104879159506246 596
0.7415958870289681 597
0.6824002890177536 598
0.6929969240296272 599
0.5874319882509818 600
0.5503984856520276 601
0.5804607800711392 602
0.651504993685573 603
0.7110773557479924 604
0.7115856859622005 605
0.6059719517893931 606
0.556444257464701 607
0.45290975194586014 608
0.7288391413958465 609
0.8345199179480816 610
0.5475365693007 611
0.6551175355214196 612
0.5567150193536026 613
0.5557580740491337 614
0.7784479326770812 615
0.6428003139060541 616
0.7505724127120909 617
0.6546899715053764 618
0.5837763950461412 619
0.5196622347580933 620
0.6418755101521946 621
0.7666164620993304 622
0.6601764623001473 623
0.5872669162939372 624
0.6906293366009504 625
0.6940556840728622 626
0.6986863708709633 627
0.6847203356618958 628
0.5914571496184772 629
0.5779174771475131 630
0.7080371361628088 631
0.6343318436950409 632
0.7709151772874403 633
0.7309151844457016 634
0.6463026335697339 635
0.7388123236388753 636
0.540449172764045 637
0.6178742988987809 638
0.7033584524089107 639
0.6374204774074308 640
0.7150421487366386 641
0.5084376945202815 642
0.5114004497245532 643
0.6088932556543429 644
0.5676166899093533 645
0.6343734050542346 646
0.7147758198410807 647
0.7325408361218118 648
0.5816852381928376 649
0.7300124804815483 650
0.5956489510368865 651
0.5403353558931259 652
0.8057837584246046 653
0.6286134915584642 654
0.5900511072741454 655
0.519045600434485 656
0.7034827467798703 657
0.44947079019993774 658
0.7770109349299585 659
0.7391004321276371 660
0.4664742630456151 661
0.6421818322273541 662
0.6464765896743865 663
0.7895591721935757 664
0.4914583757269858 665
0.7255424597495077 666
0.40479912013887476 667
0.5873136632127904 668
0.6933104318600686 669
0.601186805737103 670
0.6736990444946085 671
0.7398003193303377 672
0.7493460109754206 673
0.5402076028069154 674
0.4214111509193461 675
0.5296503535669784 676
0.6044467452287804 677
0.7598487702923276 678
0.5677960420017132 679
0.7864885519784387 680
0.7693594822680156 681
0.6611668637289261 682
0.6220596795046143 683
0.5477467363989386 684
0.5452555917736264 685
0.5548637559178543 686
0.6324820762807859 687
0.6394347256179809 688
0.6554893755274188 689
0.6845221081539723 690
0.691262495129784 691
0.6052218951230844 692
0.6713354415846351 693
0.6701175790440596 694
0.6037557361505587 695
0.5214103639966385 696
0.6038357655598505 697
0.7272842363501429 698
0.5736582574253117 699
0.7470299727877057 700
0.6149087825164987 701
0.6384300000608345 702
0.6687249590677172 703
0.8364125643435691 704
0.6550309864675221 705
0.7334531521661807 706
0.6186199913617875 707
0.6917796411081326 708
0.6085517057542134 709
0.6517648732609276 710
0.7554509609666626 711
0.5082416959285259 712
0.46638083939103625 713
0.6291258313508648 714
0.47433149655492524 715
0.7071903388645746 716
0.4377530329480688 717
0.6941594245646933 718
0.6573262686119856 719
0.7306652769003673 720
0.49826842045359965 721
0.6887470926104908 722
0.5472235403732026 723
0.5527617744887068 724
0.7301508735386396 725
0.7354057398905585 726
0.7898209354280649 727
0.6036265208604155 728

0.5892337680992705 729
0.6773568082797322 730
0.6536037006594648 731
0.713529656457005 732
0.4645907506917969 733
0.6041828611263727 734
0.7252381063452615 735
0.7080367303467395 736
0.5360419498499773 737
0.6344436078373403 738
0.6334378506215028 739
0.7057374689239049 740
0.49767925578124306 741
0.6641049293620375 742
0.7470471131654517 743
0.6143021196290908 744
0.7080391279517827 745
0.46542494266747225 746
0.6979287290891099 747
0.7481386554241547 748
0.569748553170754 749
0.6193215717624957 750
0.5726931338120993 751
0.5914780376184695 752
0.5972569848685649 753
0.6829049770504521 754
0.6335426875293433 755
0.675247681683931 756
0.6557546006925096 757
0.5902109126495245 758
0.6416936993115157 759
0.6529292998069238 760
0.6784494524943596 761
0.7059731618331576 762
0.6246294133885555 763
0.6914984004090534 764
0.6001181899949184 765
0.636804664381496 766
0.7215703567339238 767
0.6644778802932718 768
0.6811913566845742 769
0.673381169109013 770
0.6430562518638543 771
0.579524782903759 772
0.7303278068314698 773
0.6377898049435692 774
0.6978820780781589 775
0.726640506041596 776
0.657802398761784 777
0.6183266188078773 778
0.6197053639689734 779
0.6713753171146494 780
0.70855131911149 781
0.7264802505035046 782
0.6223970172783058 783
0.6303745559701193 784
0.48467763287842414 785
0.6884081559389137 786
0.6043328925618705 787
0.6622902619460262 788
0.546359049157938 789
0.5995747059176317 790
0.6812099274357384 791
0.7150985521064441 792
0.4827178092155159 793
0.5799926894818321 794
0.7370609656906837 795
0.5547703045383503 796
0.62077760237893 797
0.7121123782624852 798
0.4736341406924133 799
0.6726637215070055 800
0.724302009341468 801
0.6076906889235958 802
0.6779981073997532 803
0.6559153160991 804
0.7114804131666823 805
0.5637923430377226 806
0.7263957587487861 807
0.5821986335713019 808
0.7752336629986714 809
0.5412739605883853 810
0.7151034892626433 811
0.5766149574620345 812
0.6951470170767542 813
0.6405134623272117 814
0.4716259798491712 815
0.6625048741386355 816
0.6776857936016596 817
0.7334940120979372 818
0.5987838625903541 819
0.3688715498946362 820
0.658946464586322 821
0.7290338207592206 822
0.7163340407743148 823
0.606761475818975 824
0.6049916080235267 825
0.6203331249643647 826
0.6241165422348814 827
0.721063196454052 828
0.6494460686181841 829
0.6323464642333113 830
0.7540281737915122 831
0.6065876842313402 832
0.6639726697527966 833
0.6728302569820198 834
0.4645776110749609 835
0.5864683125938535 836
0.7150249327717871 837
0.732028655290518 838
0.5726777746649181 839
0.5170482747986683 840
0.7859994778150565 841
0.7521397064039839 842
0.6278807944546814 843
0.7851909715155875 844
0.6176596225429519 845
0.6515886856438623 846
0.6939196176172308 847
0.6213509177625005 848
0.5419205432515787 849
0.6011951090504233 850
0.6218560548581424 851
0.5601212883004646 852
0.7303372138962503 853
0.7045486354167222 854
0.6931765060040804 855
0.5778054524327553 856
0.6541345892001564 857
0.6611960379733137 858
0.5657154548882878 859
0.6567530835968496 860
0.8089832437934187 861
0.6754218260039551 862
0.6160941024143354 863
0.6252970765454656 864
0.47219648879900433 865
0.5838985320029123 866
0.7350818580541909 867
0.6834003367261394 868
0.6614011681232597 869
0.6163773193899313 870
0.6421445451395171 871
0.7947540414955606 872
0.6949352419534682 873
0.7076075859023248 874
0.7007428779650196 875
0.7179114450136629 876
0.47120504993797874 877
0.7319263996761132 878
0.6261936813690815 879
0.5058997229655087 880
0.7652992036607298 881
0.6365164018178481 882
0.6936585144664122 883
0.5648607122525722 884
0.7359025734127809 885
0.7738603597324621 886
0.6109903380480106 887
0.5232915431450351 888
0.5209152423622638 889
0.7186762096380699 890
0.566787175712416 891
0.6534842480354162 892
0.6977491022040692 893
0.6122734641820171 894
0.6037871461828066 895
0.5847642480244948 896
0.6571323341603936 897
0.4698130006929393 898
0.39382237558147903 899
0.810970655825075 900
0.6247107252425723 901
0.6347948721784047 902
0.6392900106961052 903
0.6280427325571942 904
0.5831207561478067 905
0.7538061305866202 906
0.5520810641412119 907
0.5618254788818231 908
0.5915229567787319 909
0.5815903366509549 910
0.556494090772667 911
0.7487758598170093 912
0.5758279209963995 913
0.657178160140047 914
0.6393640734791182 915
0.7555329478147789 916
0.5434551100557861 917
0.5196592284420994 918
0.7386517464052597 919
0.7730727749957895 920
0.6191703053400328 921
0.5076531731798162 922
0.744917483422781 923
0.6363247934876219 924
0.7507786966405288 925
0.6574787924446135 926
0.7197750425897094 927
0.5771904788088525 928
0.6649324246758597 929
0.5509928484838724 930
0.5567621163651495 931
0.7041650782110415 932
0.7809475091142021 933
0.6730635792127417 934
0.6344336203723306 935
0.8043489065460345 936
0.5938721112287739 937
0.5395395980189259 938
0.7112450026726123 939
0.729646993971564 940
0.6106683818710155 941
0.5707470619402399 942
0.5912530711096391 943
0.6066707682817392 944
0.4200750485557132 945
0.5730215728591258 946
0.6069761107594734 947
0.7259126914348776 948
0.7057838296336137 949
0.5187799252846688 950
0.6120466186057647 951
0.5352066706000902 952
0.6048495868849388 953
0.55652843910745 954
0.43948244514354473 955
0.6042050969059135 956
0.6564158075318369 957
0.5400997098718306 958
0.6011561046511101 959
0.7081489386312008 960
0.6865181584062692 961
0.643512690315517 962
0.6157403044454308 963
0.6608461078309491 964
0.6538153789601733 965
0.5443384914777668 966
0.6904268624257546 967
0.8276066185543275 968
0.45622740158553454 969
0.6768531213075057 970
0.7992066226479911 971
0.7739851493504486 972
0.615480337387818 973
0.6448172014201456 974
0.7066505608024176 975
0.5219073602311151 976
0.5291106814512345 977
0.6889477998272158 978
0.5950995893582745 979
0.7230377755363651 980
0.6810214581421503 981
0.6422930605271299 982
0.6843711141106961 983
0.6286764225311645 984
0.7205920068360023 985
0.7105226805019422 986
0.734627073839043 987
0.683262913409723 988
0.66145868479846 989
0.6716780966440032 990
0.6755187123964242 991
0.7072373420322282 992
0.6771734998814747 993
0.743743544959156 994
0.6782929357184435 995
0.5112238729283447 996
0.6444364092457882 997
0.7797030551714346 998
0.7067548629886082 999

In [44]:
np.argmax(scores)

704

In [45]:
scores[np.argmax(scores)]

0.8364125643435691

In [46]:
import pickle

In [47]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [48]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift', 'Maruti',2019,100,'Petrol']], columns=['name','company','year','kms_covered','fuel_type']))

array([466264.25807873])

In [52]:
pipe.predict(pd.DataFrame([['Hyundai Eon', 'Ford',2012,41000,'Diesel']], columns=['name','company','year','kms_covered','fuel_type']))

array([280767.09962723])

In [54]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Ritz', 'Maruti',2011,500,'Petrol']], columns=['name','company','year','kms_covered','fuel_type']))

array([157553.05202581])

In [49]:
x

                       name   company  year  kms_covered fuel_type
0       Mahindra Jeep CL550  Mahindra  2006           40    Diesel
1         Hyundai Grand i10   Hyundai  2014        28000    Petrol
2    Ford EcoSport Titanium      Ford  2014        36000    Diesel
3                 Ford Figo      Ford  2012        41000    Diesel
4               Hyundai Eon   Hyundai  2013        25000    Petrol
..                      ...       ...   ...          ...       ...
809      Maruti Suzuki Ritz    Maruti  2011        50000    Petrol
810          Tata Indica V2      Tata  2009        30000    Diesel
811    Toyota Corolla Altis    Toyota  2009       132000    Petrol
812            Tata Zest XM      Tata  2018        27000    Diesel
813      Mahindra Quanto C8  Mahindra  2013        40000    Diesel

[814 rows x 5 columns]